#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
  cp="cp -iv" \
  mv="mv -iv" \
  bc="bc -ql" \
  yt="youtube-dl --add-metadata -i" \
  yta="yt -x -f bestaudio/best" \
  ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
  ls="ls -h --color=auto" \
  grep="grep --color=auto" \
  ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
  g="git" \
  lg="lazygit" \
  c="claude" \
  s="spotify_player" \
  t="btop" \
  top="btop" \
  htop="btop" \
  k="kubectl" \
  mux="tmuxinator" \
  trem="transmission-remote" \
  YT="youtube-viewer" \
  sdn="sudo shutdown -h now" \
  v="$EDITOR" \
  k10s="devx login && devx mariner kubeconfig && k9s --context cp3-nonprod-main-us-east-1 --namespace winnie" \
  awsd="devx cloud aws-login -r 'arn:aws:iam::212883212683:role/bamazon-TeamInsights'" \
  ji="jira issue list -w -s~Done --order-by status" \
  bu="brew upgrade | tee /dev/tty | grep -q 'yabai' && yabaiheadupdate" \
  reload-shortcuts="apply-shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
  ubuntu="docker run --rm -ti ubuntu /bin/bash"
