---
- name: Register Brewfile
  stat:
    path: "{{ role_path }}/files/macos/Brewfile"
  register: brew_file

- when: brew_file.stat.exists
  block:
    - name: Check if install is needed
      command: "brew bundle check --file={{ brew_file.stat.path }}"
      register: brew_check
      changed_when: false
      failed_when: false

    - name: Install from Brewfile
      when: brew_check.rc == 1
      command: "brew bundle --no-lock --file={{ brew_file.stat.path }}"
      changed_when: false
      async: 100000
      poll: 5

- name: Update all homebrew packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
