---
- name: Create config directories to prevent stow conflicts
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  loop:
    - .local/bin
    - .local/share
    - .config
    - .zshrc.d

- name: Set dotfiles templating facts
  set_fact:
    dotfiles_src: "{{ role_path }}/files"

- block:
    - name: Ensure dotfiles home exists
      file:
        path: "{{ dotfiles_home }}"
        state: directory

    - name: Find all dotfiles
      ansible.builtin.find:
        paths:
          - "{{ dotfiles_src }}/all/"
          - "{{ dotfiles_src }}/os_{{ ansible_system }}/"
        file_type: any
        hidden: true
        recurse: true
      register: dotfiles_to_symlink

    - name: Filter out find results
      set_fact:
        dotfiles_to_symlink: "{{ dotfiles_to_symlink.files | rejectattr('isdir') | list }}"

    - name: Create destination directories
      file:
        path: "{{ dotfiles_home }}/{{ item.path | regex_replace('^' + dotfiles_src + '/(all|os_' + ansible_system + ')/', '') | dirname }}"
        state: directory
      loop: "{{ dotfiles_to_symlink }}"
      no_log: true

    - name: Template dotfiles
      template:
        src: "{{ item.path }}"
        dest: "{{ dotfiles_home }}/{{ item.path | regex_replace('^' + dotfiles_src + '/(all|os_' + ansible_system + ')/', '') | regex_replace('(.*)(\\.j2)$', '\\1') }}"
      with_items: "{{ dotfiles_to_symlink }}"
      when: "item.path.endswith('.j2')"

    - name: Create a relative symlink for dotfiles
      command: ln -fsr "{{ item.path }}" "{{ dotfiles_home }}/{{ item.path | regex_replace('^' + dotfiles_src + '/(all|os_' + ansible_system + ')/', '') }}"
      loop: "{{ dotfiles_to_symlink }}"
      when: "not item.path.endswith('.j2')"

- block:
    - name: stow dotfiles
      stow:
        state: '{{ dotfiles_state }}'
        dir: "{{ dotfiles_home }}"
        package: '{{ item }}'
      loop: "{{ stow_common_items }}"
  environment:
    PATH: "{{ homebrew_brew_bin_path | default('') }}:{{ ansible_env.PATH }}" # TODO setup PATH to discover stow for linux too

- name: Include additional setup
  ansible.builtin.include_tasks: "additional_setup.yaml"
