import = ["/Users/nickyasnogorodskyi/.config/alacritty/tokyonight-storm.toml"]
live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "LBracket"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[mouse]
hide_when_typing = false


[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",?`|:\"' ()[]{}<>"

[shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_title = false
option_as_alt = "Both"
startup_mode = "Windowed"

[window.padding]
x = 2
