[tools]
# Languages & runtimes
node = "22"
python = "3.14"
go = "latest"
uv = "latest"
bun = "latest"
deno = "latest"
rust = "latest"
dotnet = "9"
lua = "latest"

terraform = "latest"
dprint = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"cargo:https://github.com/euclio/mdpls" = "HEAD"
"pipx:ty" = "latest"

[hooks]
postinstall = 'corepack enable pnpm'

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "python", "go"]

[settings.python]
uv_venv_auto = "create|source"
