
# tap repositories and their packages

tap nikitabobko/tap
cask aerospace

tap raine/claude-history
brew claude-history

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew bash
brew bat
brew bottom
brew ccusage
brew duti
brew fd
brew fish
brew fzf
brew gh
brew helix
brew imagemagick
brew jq
brew lazygit
brew lua-language-server
brew make
brew mas
brew mergiraf
brew mise
brew ruff
brew stow
brew stylua
brew taplo
brew vscode-langservers-extracted
brew yaml-language-server
brew yazi
brew zoxide

# Other Cask applications
cask firefox
cask font-jetbrains-mono-nerd-font
cask google-chrome
cask hiddenbar
cask kitlangton-hex
cask linearmouse
cask monitorcontrol
cask spotify
cask wezterm@nightly

# Main file
main ./Brewfile.$HOSTNAME
