
# tap repositories and their packages

brew bash
brew biome
brew bottom
brew ccusage
brew duti
brew exiftool
brew fd
brew ffmpeg
brew fish
brew fzf
brew gh
brew git-delta
brew grep
brew helix
brew imagemagick
brew jq
brew lazygit
brew libarchive
brew lua
brew lua-language-server
brew luajit
brew make
brew mas
brew mergiraf
brew mise
brew poppler
brew ruff
brew rust
brew scc
brew speedtest-cli
brew stow
brew stylua
brew taplo
brew trash-cli
brew vscode-langservers-extracted
brew yaml-language-server
brew yazi

cask claude-code
cask codex
cask firefox
cask font-jetbrains-mono-nerd-font
cask font-symbols-only-nerd-font
cask gimp
cask google-chrome
cask google-drive
cask handbrake-app
cask hiddenbar
cask insta360-studio
cask karabiner-elements
cask kitlangton-hex
cask linearmouse
cask monitorcontrol
cask ngrok
cask orbstack
cask quarto
cask rawtherapee
cask readdle-spark
cask spotify
cask vlc
cask wezterm@nightly
cask zed
cask zoom

tap mhaeuser/mhaeuser

tap nikitabobko/tap
cask aerospace

tap raine/claude-history
brew claude-history

tap rcmdnk/file
brew brew-file

tap walavave/tap

# Main file
main ./Brewfile.$HOSTNAME
