
# tap repositories and their packages

tap librespeed/tap
brew librespeed-cli

tap nikitabobko/tap
cask aerospace

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew ansible-language-server
brew automake
brew bash
brew bat
brew bottom
brew btop
brew ccusage
brew duti
brew fd
brew fish
brew fzf
brew gh
brew grep
brew handbrake
brew helix
brew htop
brew imagemagick
brew k9s
brew lazydocker
brew lazygit
brew lua-language-server
brew make
brew markdown-oxide
brew marksman
brew mas
brew mergiraf
brew mise
brew mpv
brew nmap
brew pug
brew ruff
brew scc
brew sevenzip
brew stow
brew stylua
brew taplo
brew terraform-ls
brew tesseract
brew trash
brew trash-cli
brew tree
brew vscode-langservers-extracted
brew yaml-language-server
brew yazi
brew zoxide

# Other Cask applications
cask brave-browser
cask codex
cask dbeaver-community
cask firefox
cask font-jetbrains-mono-nerd-font
cask font-symbols-only-nerd-font
cask handbrake-app
cask hiddenbar
cask karabiner-elements
cask kitlangton-hex
cask linearmouse
cask microsoft-teams
cask monitorcontrol
cask ngrok
cask obs
cask obsidian
cask spotify
cask vlc
cask wezterm@nightly
cask zed
cask zoom

# Main file
main ./Brewfile.$HOSTNAME
