#!/usr/bin/env sh

export YABAI="$HOME/.config/yabai/scripts"

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &
sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_destroyed action=$YABAI/focus_space.sh
yabai -m signal --add event=window_minimized action=$YABAI/focus_space.sh
yabai -m signal --add event=application_hidden action=$YABAI/focus_space.sh
# yabai -m signal --add event=display_added action="sleep 1 && $YABAI/create_spaces.sh 6"
# yabai -m signal --add event=display_removed action="sleep 1 && $YABAI/create_spaces.sh 6"

yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_shadow float \
  window_zoom_persist off \
  window_opacity off \
  menubar_opacity 1.0 \
  normal_window_opacity 0.6 \
  window_animation_duration 0.0 \
  insert_feedback_color 0xff9dd274 \
  layout bsp \
  split_type auto \
  split_ratio 0.5 \
  auto_balance off \
  mouse_modifier ctrl \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  window_gap 4 \
  debug_output off

# App-specific rules
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='^General' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off grid=20:20:6:4:12:12
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add title="Steam" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add title="QuickTerminal" grid=40:20:4:7:12:26 opacity=0.9 scratchpad="QuickTerminal" sticky=on

# Space-specific rules
yabai -m rule --add app="Spotify" space=5
yabai -m rule --add app="YouTube Music" space=5
yabai -m rule --add app="Spark Desktop" title="Spark Desktop" space=6

$YABAI/create_spaces.sh 6
skhd &
echo "yabai configuration loaded.."
