theme = "catppuccin_mocha"

[editor]
bufferline = "always"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal.space]
g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":set mouse false", # First disable mouse to hint helix into activating it
    ":set mouse true",
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
