after-login-command = []
after-startup-command = []

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 120

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# This triggers when you close the lid because the "focused monitor" shifts to the DELL.
# We add a 0.5s sleep to wait for macOS to finish moving workspaces before we force "Code".
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

# See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[workspace-to-monitor-force-assignment]
Code = 'DELL U2723QE'
Social = 'DELL U2723QE'
Data = 'DELL U2723QE'
Music = 'Built-in Retina Display'
Mail = 'DELL U2723QE'

# 'main' binding mode declaration
[mode.main.binding]
cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

ctrl-alt-cmd-q = 'close'
ctrl-alt-cmd-f = 'fullscreen'
ctrl-alt-cmd-r = 'reload-config'
ctrl-alt-cmd-t = 'layout tiles accordion'
ctrl-alt-cmd-b = 'exec-and-forget browser'
ctrl-alt-cmd-o = 'exec-and-forget open -n /System/Applications/System\ Settings.app'
ctrl-alt-cmd-e = 'exec-and-forget open -n ~/Downloads'
ctrl-alt-cmd-p = 'exec-and-forget screencapture -cix /dev/null'
ctrl-alt-cmd-enter = 'exec-and-forget terminal'
ctrl-alt-cmd-equal = 'exec-and-forget open -a "Mission Control"'
ctrl-alt-cmd-minus = 'exec-and-forget open -a "Launchpad"'
ctrl-alt-cmd-shift-p = 'exec-and-forget screencapture -Pix /dev/null'
ctrl-alt-cmd-shift-r = 'exec-and-forget screencapture -iU /dev/null'

ctrl-alt-cmd-h = 'focus left'
ctrl-alt-cmd-j = 'focus down'
ctrl-alt-cmd-k = 'focus up'
ctrl-alt-cmd-l = 'focus right'

ctrl-alt-cmd-shift-h = 'move left'
ctrl-alt-cmd-shift-j = 'move down'
ctrl-alt-cmd-shift-k = 'move up'
ctrl-alt-cmd-shift-l = 'move right'

ctrl-alt-cmd-left = 'resize width -50'
ctrl-alt-cmd-right = 'resize width +50'
ctrl-alt-cmd-down = 'resize height -50'
ctrl-alt-cmd-up = 'resize height +50'

ctrl-alt-cmd-g = 'workspace prev'
ctrl-alt-cmd-semicolon = 'workspace next'
ctrl-alt-cmd-shift-g = 'move-node-to-workspace prev'
ctrl-alt-cmd-shift-semicolon = 'move-node-to-workspace next'

ctrl-alt-cmd-0 = 'workspace-back-and-forth'
ctrl-alt-cmd-1 = 'workspace Code'
ctrl-alt-cmd-shift-1 = 'move-node-to-workspace Code'
ctrl-alt-cmd-2 = 'workspace Social'
ctrl-alt-cmd-shift-2 = 'move-node-to-workspace Social'
ctrl-alt-cmd-3 = 'workspace Data'
ctrl-alt-cmd-shift-3 = 'move-node-to-workspace Data'
ctrl-alt-cmd-8 = 'workspace Music'
ctrl-alt-cmd-shift-8 = 'move-node-to-workspace Music'
ctrl-alt-cmd-9 = 'workspace Mail'
ctrl-alt-cmd-shift-9 = 'move-node-to-workspace Mail'

ctrl-alt-cmd-tab = 'workspace-back-and-forth'
ctrl-alt-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[[on-window-detected]]
if.app-id = 'com.readdle.SparkDesktop'
run = ['move-node-to-workspace Mail']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['move-node-to-workspace Music']

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = ['move-node-to-workspace Code']

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = ['move-node-to-workspace Code']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['move-node-to-workspace Code']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['move-node-to-workspace Social']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams'
run = ['move-node-to-workspace Social']
